### ISSUE TITLE
ONIE

### ISSUE THREAD

**Issue by karthikbollam** [DeltaProducts/OpenNetworkLinux#12]
Can snaproute get access to Delta's ONIE code? That way we can update our platform ONIE  [as the string name are renamed from Agema to Delta]

**Comment by mike03052000** [comment]
We recently update the onie and know the new onie can't load the ONL image.
We're working on newer version that can load the old ONL images.

Here's the workaround solution .
1.	Enter to ONIE: install OS
2.	Stop onie install task.
        onie-discovery-stop
3.	Modify /etc/machine.conf
        onie_platform=x86_64-delta_ag9032v1-r0
        onie_machine=delta_ag9032v1
        change to 
        onie_platform=x86_64-ag9032v1-r0
        onie_machine=ag9032v1

You should be able to install the image.

**Comment by nnoei2001** [comment]
Workaround shared by mike.  Closing this issue

Enter to ONIE: install OS
Stop onie install task.
onie-discovery-stop
Modify /etc/machine.conf
onie_platform=x86_64-delta_ag9032v1-r0
onie_machine=delta_ag9032v1
change to
onie_platform=x86_64-ag9032v1-r0
onie_machine=ag9032v1
