### ISSUE TITLE
NAND Errors

### ISSUE THREAD

**Issue by jerrchen** [DeltaProducts/OpenNetworkLinux#4]
"I pulled changes from Agema branch and ONL tried to install but we have a ag6248 with bad NAND. During ubiformat it fails and installation stops.

UBI ERROR:
ubiformat: 4 bad eraseblocks found, numbers: 74, 75, 93, 101
Install failed. See log messages above for details"

**Comment by jerrchen** [comment]
The NAND error was not significant, the problem with our customer is they changed some of the partition mapping. 

Need a way to increase ONL_DATA partition to beyond 2G.  @XiongJunDelta  can you help?

The customer tried to change below, but it is not working for them 


 + -
ONL-BOOT:
 +
=:
128MiB
 +
format:
ubifs
 + -
ONL-CONFIG:
 +
=:
128MiB
 +
format:
ubifs
 + -
ONL-IMAGES:
 +
=:
1024MiB
 +
format:
ubifs
 + -
ONL-DATA:
 +
=:
2048MiB
 +
format:
ubifs

**Comment by XiongJunDelta** [comment]
the partition of current code is the same with the customer's requried.
you can modify the partition at packages/platforms/agema/.rmel/arm-agema-ag6248c/arm-agema-ag6248c/platform-config/r0/src/lib/arm-agema-ag6248c-r0.yml,

**Comment by jerrchen** [comment]
@XiongJunDelta   can you paste the changed .yml file here please?

**Comment by XiongJunDelta** [comment]
the mtd part 4 only have about 3.8GB space, so please decrease the images partition and increase the data partition. the below partition has been verified at my side.
  installer:
  - ONL-BOOT:
      =: 128MiB
      format: ubifs
  - ONL-CONFIG:
      =: 128MiB
      format: ubifs
  - ONL-IMAGES:
      =: 512MiB
      format: ubifs
  - ONL-DATA:
      =: 3072MiB
      format: ubifs
