### ISSUE TITLE
Need ONIE image/code for WB2448

### ISSUE THREAD

**Issue by karthikbollam** [DeltaProducts/OpenNetworkLinux#6]
In the upstream ONL WB2448 platform support is added as Delta WB2448, but the switch we have has ONIE that says DNI. Could you forward ONIE image that has platform string set to "x86-64-delta-wb2448-r0", or ONIE code with that string.

**Comment by jerrchen** [comment]
@karthikbollam following up with the team now.

**Comment by louiskao324** [comment]
I already pushed new onie image that changed platform name to delta in below link.
https://github.com/DeltaProducts/WB2448/tree/master/onie
